Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,9 +15,9 @@ jobs:
     runs-on: windows-latest
     strategy:
       matrix:
-        python-version: ['3.11']  # Adjust based on the Python version you need
+        python-version: ['3.11']
     env:
-      VS_PLATFORM: x64  # Target 64-bit architecture
+      VS_PLATFORM: x64
     steps:
       # Step 1: Check out the repository
       - uses: actions/checkout@v4
@@ -28,36 +28,47 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
 
-      # Step 3: Download TA-Lib Source Files (using .zip)
+      # Step 3: Download TA-Lib Source Files
       - name: Download TA-Lib source files
         run: |
           echo "Downloading TA-Lib source files..."
           powershell -Command "Invoke-WebRequest -Uri https://sourceforge.net/projects/ta-lib/files/ta-lib/0.4.0/ta-lib-0.4.0-msvc.zip -OutFile ta-lib-src.zip"
-          powershell -Command "Expand-Archive -Path ta-lib-src.zip -DestinationPath ."
-          echo "TA-Lib source files downloaded and extracted."
+          if (Test-Path ta-lib-src.zip) {
+            echo "TA-Lib source files downloaded successfully."
+          } else {
+            echo "Error: TA-Lib source files failed to download."
+            exit 1
 
-      # Step 4: Move TA-Lib source files to expected directory structure
+      # Step 4: Extract TA-Lib Source Files
+      - name: Extract TA-Lib source files
+        run: |
+          echo "Extracting TA-Lib source files..."
+          powershell -Command "Expand-Archive -Path ta-lib-src.zip -DestinationPath ."
+          echo "Listing the extracted files:"
+          Get-ChildItem -Recurse
+
+      # Step 5: Move TA-Lib source files to the expected directory structure
       - name: Organize TA-Lib source files
         run: |
           mkdir -p ta-lib/c/src
           move ta-lib-0.4.0-msvc/* ta-lib/c/src
-          echo "TA-Lib files moved to correct location."
+          echo "TA-Lib files moved to the correct location."
 
-      # Step 5: Install build dependencies
+      # Step 6: Install build dependencies
       - name: Install Build Dependencies
         run: |
           python -m pip install --upgrade pip
           pip install setuptools wheel numpy Cython
           pip install pytest
 
-      # Step 6: Build the TA-Lib wheel
+      # Step 7: Build the TA-Lib wheel
       - name: Build TA-Lib Wheel
         run: |
           set LIB="ta-lib\\c\\ide\\vs2022\\lib_proj\\x64;$LIB"
           python setup.py bdist_wheel
         working-directory: ta-lib/c/src
 
-      # Step 7: Upload the built wheel as an artifact
+      # Step 8: Upload the built wheel as an artifact
       - name: Upload Wheel Artifact
         uses: actions/upload-artifact@v4
         with:
